# Sample workflow for building and deploying a Gatsby site to GitHub Pages
#
# To get started with Gatsby see: https://www.gatsbyjs.com/docs/quick-start/
#
name: Deploy Gatsby site to Server

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - orbitowebhook

jobs:
  # Build job
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3     

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.4.0"

      - name: Setup Node and Install dependencies       
        run: npm install

    

      - name: Build with Gatsby
        run: npm run build
        
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: gaysby-build
          path: public

  # Deploy job
  deploy:
    needs: build
    runs-on: windows-latest
    
    steps:                  
      #- name: Download a single artifact
       # uses: actions/download-artifact@v3
       
      - uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: gaysby-build
          path: public
          
      - name: Open Public Folder
        run: dir
        
    
        
      - name:  FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PSW }}
          local-dir: ./public/
          server-dir: /QA/

